# Generated by Django 3.1.7 on 2021-09-24 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ManageApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmovement',
            name='from_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_location', to='ManageApp.location'),
        ),
        migrations.AlterField(
            model_name='productmovement',
            name='to_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_location', to='ManageApp.location'),
        ),
    ]
