# Generated by Django 3.1.7 on 2021-09-26 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ManageApp', '0007_auto_20210926_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmovement',
            name='location',
        ),
    ]
