# Generated by Django 3.1.7 on 2021-09-28 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ManageApp', '0009_issue_receive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='to_location',
        ),
        migrations.DeleteModel(
            name='Receive',
        ),
        migrations.DeleteModel(
            name='Issue',
        ),
    ]
