# Generated by Django 3.1.7 on 2021-09-28 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ManageApp', '0012_location_product_productmovement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmovement',
            name='warehouse',
        ),
    ]
