# Generated by Django 3.1.7 on 2021-09-28 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ManageApp', '0015_location_product_productmovement'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p_warehouse', to='ManageApp.warehousename'),
        ),
        migrations.AlterField(
            model_name='productmovement',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pm_warehouse', to='ManageApp.warehousename'),
        ),
    ]
