# Generated by Django 3.1.7 on 2021-09-28 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ManageApp', '0018_auto_20210928_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='warehouse',
        ),
        migrations.RemoveField(
            model_name='productmovement',
            name='from_location',
        ),
        migrations.RemoveField(
            model_name='productmovement',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='productmovement',
            name='to_location',
        ),
        migrations.RemoveField(
            model_name='productmovement',
            name='warehouse',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductMovement',
        ),
        migrations.DeleteModel(
            name='WarehouseName',
        ),
    ]
