# Generated by Django 3.1.7 on 2021-09-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageApp', '0020_auto_20210928_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='warehouse',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='productmovement',
            name='warehouse',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='WarehouseName',
        ),
    ]
